using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Json;
using GitChurnCalculator.Models;

namespace GitChurnCalculator.Console.Reporting;

public sealed class HtmlTimeSeriesGraphReportGenerator : ITimeSeriesReportGenerator
{
    private const int TopFileLimit = 50;

    private const string BootstrapCssCdn =
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css";

    private const string D3Cdn = "https://cdn.jsdelivr.net/npm/d3@7/+esm";

    public string Generate(IReadOnlyList<TimeSeriesPoint> points, string subtitle)
    {
        var inv = CultureInfo.InvariantCulture;
        var series = BuildSeries(points);
        var seriesJson = JsonSerializer.Serialize(
            series,
            ChurnReportsJsonContext.Default.IReadOnlyListTimeSeriesGraphSeries);

        var sb = new StringBuilder(96_000);
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"utf-8\" />");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
        sb.AppendLine("  <title>Git churn risk graph</title>");
        sb.Append("  <link href=\"").Append(BootstrapCssCdn).Append("\" rel=\"stylesheet\"");
        sb.AppendLine(" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer-when-downgrade\" />");
        AppendStyles(sb);
        sb.AppendLine("</head>");
        sb.AppendLine("<body class=\"bg-light\">");
        sb.AppendLine("  <div class=\"container-fluid py-4\">");
        sb.AppendLine("    <header class=\"mb-4\">");
        sb.AppendLine("      <h1 class=\"h2\">Git churn risk graph</h1>");
        sb.Append("      <p class=\"text-muted mb-0\"><code>").Append(WebUtility.HtmlEncode(subtitle)).AppendLine("</code></p>");
        sb.Append("      <p class=\"small text-secondary\">")
            .Append(WebUtility.HtmlEncode(points.Count.ToString(inv)))
            .Append(" time points, ")
            .Append(WebUtility.HtmlEncode(series.Count.ToString(inv)))
            .Append(" top file series")
            .AppendLine("</p>");
        sb.AppendLine("    </header>");

        if (series.Count == 0)
        {
            sb.AppendLine("    <div class=\"alert alert-secondary\">No graph data to display.</div>");
        }
        else
        {
            sb.AppendLine("    <div class=\"card shadow-sm\">");
            sb.AppendLine("      <div class=\"card-body position-relative\">");
            sb.AppendLine("        <div id=\"churn-graph\"></div>");
            sb.AppendLine("        <div id=\"churn-tooltip\" class=\"graph-tooltip d-none\"></div>");
            sb.AppendLine("        <p class=\"small text-secondary mb-0 mt-3\">Hover a line or file label to highlight one file. Y-axis shows churn risk score. The tooltip lists coverage, cumulative lines added and removed (per <code class=\"small\">git log --numstat</code>), averages at the hovered snapshot (lines committed per merge count), and when the graph has multiple time steps averages of line deltas between successive steps.</p>");
            sb.AppendLine("      </div>");
            sb.AppendLine("    </div>");
        }

        sb.AppendLine("    <footer class=\"mt-3 small text-secondary\">Generated by GitChurnCalculator</footer>");
        sb.AppendLine("  </div>");
        AppendScript(sb, seriesJson);
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        return sb.ToString();
    }

    private static IReadOnlyList<TimeSeriesGraphSeries> BuildSeries(IReadOnlyList<TimeSeriesPoint> points)
    {
        return points
            .SelectMany(point => point.Files.Select(file => new { point.AsOf, File = file }))
            .GroupBy(item => item.File.FilePath, StringComparer.Ordinal)
            .OrderByDescending(group => group.Max(item => item.File.ChurnRiskScore))
            .ThenBy(group => group.Key, StringComparer.Ordinal)
            .Take(TopFileLimit)
            .Select(group =>
            {
                var ordered = group.OrderBy(item => item.AsOf).ToList();

                double? avgDeltaAdded = null;
                double? avgDeltaRemoved = null;
                if (ordered.Count >= 2)
                {
                    var sumAdded = 0L;
                    var sumRemoved = 0L;
                    for (var i = 1; i < ordered.Count; i++)
                    {
                        sumAdded += ordered[i].File.LinesAdded - ordered[i - 1].File.LinesAdded;
                        sumRemoved += ordered[i].File.LinesRemoved - ordered[i - 1].File.LinesRemoved;
                    }

                    var n = ordered.Count - 1;
                    avgDeltaAdded = Math.Round(sumAdded / (double)n, 2);
                    avgDeltaRemoved = Math.Round(sumRemoved / (double)n, 2);
                }

                return new TimeSeriesGraphSeries
                {
                    FilePath = group.Key,
                    AvgDeltaLinesAddedPerBucket = avgDeltaAdded,
                    AvgDeltaLinesRemovedPerBucket = avgDeltaRemoved,
                    Points = ordered
                        .Select(item =>
                        {
                            var f = item.File;
                            int tc = f.TotalCommits;
                            return new TimeSeriesGraphPoint
                            {
                                Date = item.AsOf.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
                                ChurnRiskScore = f.ChurnRiskScore,
                                ChangesPerWeek = f.ChangesPerWeek,
                                LinesAdded = f.LinesAdded,
                                LinesRemoved = f.LinesRemoved,
                                CoveragePercent = f.CoveragePercent,
                                LinesAddedAvgPerCommit =
                                    tc > 0 ? Math.Round((double)f.LinesAdded / tc, 2) : null,
                                LinesRemovedAvgPerCommit =
                                    tc > 0 ? Math.Round((double)f.LinesRemoved / tc, 2) : null,
                            };
                        })
                        .ToArray(),
                };
            })
            .ToArray();
    }

    private static void AppendStyles(StringBuilder sb)
    {
        sb.AppendLine("  <style>");
        sb.AppendLine("    #churn-graph { height: min(75vh, 900px); min-height: 480px; }");
        sb.AppendLine("    #churn-graph svg { width: 100%; height: 100%; overflow: visible; }");
        sb.AppendLine("    .graph-line { fill: none; stroke-width: 1.5; stroke-opacity: 0.55; }");
        sb.AppendLine("    .graph-line:hover, .graph-line.is-active { stroke-width: 3; stroke-opacity: 1; }");
        sb.AppendLine("    .legend-item { cursor: default; }");
        sb.AppendLine("    .legend-item:hover .legend-label, .legend-item.is-active .legend-label { font-weight: 600; fill: #212529; }");
        sb.AppendLine("    .graph-tooltip { position: fixed; pointer-events: none; max-width: 440px; padding: 0.5rem 0.75rem; color: #fff; background: rgba(33, 37, 41, 0.95); border-radius: 0.375rem; box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15); font-size: 0.875rem; z-index: 1080; line-height: 1.35; }");
        sb.AppendLine("    .graph-tooltip code { color: #f8f9fa; }");
        sb.AppendLine("    .axis-label, .legend-label { fill: #495057; font-size: 12px; }");
        sb.AppendLine("    .grid line { stroke: #dee2e6; stroke-opacity: 0.8; shape-rendering: crispEdges; }");
        sb.AppendLine("    .grid path { stroke-width: 0; }");
        sb.AppendLine("  </style>");
    }

    private static void AppendScript(StringBuilder sb, string seriesJson)
    {
        sb.AppendLine("  <script type=\"module\">");
        sb.Append("    import * as d3 from \"").Append(D3Cdn).AppendLine("\";");
        sb.Append("    const series = ").Append(seriesJson).AppendLine(";");
        sb.AppendLine("    if (series.length > 0) {");
        sb.AppendLine("      const parseDate = d3.timeParse('%Y-%m-%d');");
        sb.AppendLine("      const data = series.map((line) => ({");
        sb.AppendLine("        filePath: line.filePath,");
        sb.AppendLine("        avgDeltaLinesAddedPerBucket: line.avgDeltaLinesAddedPerBucket ?? null,");
        sb.AppendLine("        avgDeltaLinesRemovedPerBucket: line.avgDeltaLinesRemovedPerBucket ?? null,");
        sb.AppendLine("        points: line.points.map((point) => ({");
        sb.AppendLine("          date: parseDate(point.date),");
        sb.AppendLine("          value: point.churnRiskScore,");
        sb.AppendLine("          changesPerWeek: point.changesPerWeek,");
        sb.AppendLine("          linesAdded: point.linesAdded,");
        sb.AppendLine("          linesRemoved: point.linesRemoved,");
        sb.AppendLine("          coveragePercent: point.coveragePercent ?? null,");
        sb.AppendLine("          linesAddedAvgPerCommit: point.linesAddedAvgPerCommit ?? null,");
        sb.AppendLine("          linesRemovedAvgPerCommit: point.linesRemovedAvgPerCommit ?? null");
        sb.AppendLine("        }))");
        sb.AppendLine("      }));");
        sb.AppendLine("      const container = document.querySelector('#churn-graph');");
        sb.AppendLine("      const tooltip = d3.select('#churn-tooltip');");
        sb.AppendLine("      const allPoints = data.flatMap((line) => line.points);");
        sb.AppendLine("      const margin = { top: 24, right: 280, bottom: 52, left: 72 };");
        sb.AppendLine("      const color = d3.scaleOrdinal(data.map((line) => line.filePath), d3.schemeTableau10);");
        sb.AppendLine("      const bisectDate = d3.bisector((point) => point.date).left;");
        sb.AppendLine("      const formatScore = d3.format(',.4f');");
        sb.AppendLine("      const formatFrequency = d3.format(',.2f');");
        sb.AppendLine("      const formatInt = d3.format(',');");
        sb.AppendLine("      const formatMaybe2 = (x) => (x == null || Number.isNaN(x) ? '—' : d3.format('.2f')(x));");
        sb.AppendLine("      const formatCoverage = (x) => (x == null || Number.isNaN(x) ? '—' : `${d3.format('.2f')(x)}%`);");
        sb.AppendLine("      const escapeHtml = (value) => String(value)");
        sb.AppendLine("        .replace(/&/g, '&amp;')");
        sb.AppendLine("        .replace(/</g, '&lt;')");
        sb.AppendLine("        .replace(/>/g, '&gt;')");
        sb.AppendLine("        .replace(/\"/g, '&quot;')");
        sb.AppendLine("        .replace(/'/g, '&#39;');");
        sb.AppendLine("      const svg = d3.select(container)");
        sb.AppendLine("        .append('svg')");
        sb.AppendLine("        .attr('role', 'img')");
        sb.AppendLine("        .attr('aria-label', 'Multi-line chart of churn risk by file over time');");
        sb.AppendLine("      const nearestPoint = (points, date) => {");
        sb.AppendLine("        if (!date) return points.reduce((best, point) => point.value > best.value ? point : best, points[0]);");
        sb.AppendLine("        const index = bisectDate(points, date, 1);");
        sb.AppendLine("        const left = points[index - 1];");
        sb.AppendLine("        const right = points[index];");
        sb.AppendLine("        if (!right) return left;");
        sb.AppendLine("        return date - left.date > right.date - date ? right : left;");
        sb.AppendLine("      };");
        sb.AppendLine("      const showTooltip = (event, lineData, xScale) => {");
        sb.AppendLine("        const mouseX = xScale ? d3.pointer(event, svg.node())[0] : null;");
        sb.AppendLine("        const point = nearestPoint(lineData.points, xScale ? xScale.invert(mouseX) : null);");
        sb.AppendLine("        const date = d3.timeFormat('%Y-%m-%d')(point.date);");
        sb.AppendLine("        const seriesAvgAdded = formatMaybe2(lineData.avgDeltaLinesAddedPerBucket);");
        sb.AppendLine("        const seriesAvgRemoved = formatMaybe2(lineData.avgDeltaLinesRemovedPerBucket);");
        sb.AppendLine("        const perCommitAvg = (");
        sb.AppendLine("          point.linesAddedAvgPerCommit != null && point.linesRemovedAvgPerCommit != null");
        sb.AppendLine("            ? `<div>Avg lines added/commit: ${formatMaybe2(point.linesAddedAvgPerCommit)}</div>`");
        sb.AppendLine("              + `<div>Avg lines removed/commit: ${formatMaybe2(point.linesRemovedAvgPerCommit)}</div>`");
        sb.AppendLine("            : ''");
        sb.AppendLine("        );");
        sb.AppendLine("        const seriesAvgHtml = lineData.avgDeltaLinesAddedPerBucket !== null && lineData.avgDeltaLinesRemovedPerBucket !== null ?");
        sb.AppendLine("          '<div style=\"height:1px;background:rgba(255,255,255,0.22);margin:0.38rem 0\"></div>'");
        sb.AppendLine("          + '<div style=\"opacity:0.9;font-size:0.8125rem\">Across time series (Δ between plotted steps)</div>'");
        sb.AppendLine("          + `<div>Avg Δ lines added: ${seriesAvgAdded}</div>`");
        sb.AppendLine("          + `<div>Avg Δ lines removed: ${seriesAvgRemoved}</div>`");
        sb.AppendLine("          : '';");
        sb.AppendLine("        tooltip");
        sb.AppendLine("          .classed('d-none', false)");
        sb.AppendLine("          .html(");
        sb.AppendLine("            `<div><code>${escapeHtml(lineData.filePath)}</code></div>`");
        sb.AppendLine("            + `<div>Date: ${date}</div>`");
        sb.AppendLine("            + `<div>Churn risk: ${formatScore(point.value)}</div>`");
        sb.AppendLine("            + `<div>Changes/week: ${formatFrequency(point.changesPerWeek)}</div>`");
        sb.AppendLine("            + `<div>Coverage: ${formatCoverage(point.coveragePercent)}</div>`");
        sb.AppendLine("            + `<div>Lines added (cum.): ${formatInt(point.linesAdded)}</div>`");
        sb.AppendLine("            + `<div>Lines removed (cum.): ${formatInt(point.linesRemoved)}</div>`");
        sb.AppendLine("            + perCommitAvg");
        sb.AppendLine("            + seriesAvgHtml");
        sb.AppendLine("          )");
        sb.AppendLine("          .style('left', `${event.clientX + 14}px`)");
        sb.AppendLine("          .style('top', `${event.clientY + 14}px`);");
        sb.AppendLine("      };");
        sb.AppendLine("      const hideTooltip = () => tooltip.classed('d-none', true);");
        sb.AppendLine("      const highlight = (filePath, active) => {");
        sb.AppendLine("        svg.selectAll('.graph-line')");
        sb.AppendLine("          .classed('is-active', (lineData) => active && lineData.filePath === filePath)");
        sb.AppendLine("          .filter((lineData) => active && lineData.filePath === filePath)");
        sb.AppendLine("          .raise();");
        sb.AppendLine("        svg.selectAll('.legend-item')");
        sb.AppendLine("          .classed('is-active', (lineData) => active && lineData.filePath === filePath);");
        sb.AppendLine("      };");
        sb.AppendLine("      const render = () => {");
        sb.AppendLine("        const bounds = container.getBoundingClientRect();");
        sb.AppendLine("        const width = Math.max(760, Math.floor(bounds.width));");
        sb.AppendLine("        const height = Math.max(480, Math.floor(bounds.height));");
        sb.AppendLine("        svg.attr('viewBox', [0, 0, width, height]);");
        sb.AppendLine("        svg.selectAll('*').remove();");
        sb.AppendLine("        const x = d3.scaleTime()");
        sb.AppendLine("          .domain(d3.extent(allPoints, (point) => point.date))");
        sb.AppendLine("          .range([margin.left, width - margin.right]);");
        sb.AppendLine("        const y = d3.scaleLinear()");
        sb.AppendLine("          .domain([0, d3.max(allPoints, (point) => point.value) || 1]).nice()");
        sb.AppendLine("          .range([height - margin.bottom, margin.top]);");
        sb.AppendLine("        const line = d3.line()");
        sb.AppendLine("          .defined((point) => point.date && Number.isFinite(point.value))");
        sb.AppendLine("          .x((point) => x(point.date))");
        sb.AppendLine("          .y((point) => y(point.value));");
        sb.AppendLine("        svg.append('g')");
        sb.AppendLine("          .attr('class', 'grid')");
        sb.AppendLine("          .attr('transform', `translate(${margin.left},0)`)");
        sb.AppendLine("          .call(d3.axisLeft(y).tickSize(-(width - margin.left - margin.right)).tickFormat(''));");
        sb.AppendLine("        svg.append('g')");
        sb.AppendLine("          .attr('transform', `translate(0,${height - margin.bottom})`)");
        sb.AppendLine("          .call(d3.axisBottom(x).ticks(Math.min(10, allPoints.length)).tickSizeOuter(0));");
        sb.AppendLine("        svg.append('g')");
        sb.AppendLine("          .attr('transform', `translate(${margin.left},0)`)");
        sb.AppendLine("          .call(d3.axisLeft(y));");
        sb.AppendLine("        svg.append('text')");
        sb.AppendLine("          .attr('class', 'axis-label')");
        sb.AppendLine("          .attr('text-anchor', 'middle')");
        sb.AppendLine("          .attr('transform', `translate(20,${height / 2}) rotate(-90)`)");
        sb.AppendLine("          .text('Churn risk score');");
        sb.AppendLine("        svg.append('g')");
        sb.AppendLine("          .selectAll('path')");
        sb.AppendLine("          .data(data)");
        sb.AppendLine("          .join('path')");
        sb.AppendLine("          .attr('class', 'graph-line')");
        sb.AppendLine("          .attr('stroke', (lineData) => color(lineData.filePath))");
        sb.AppendLine("          .attr('d', (lineData) => line(lineData.points))");
        sb.AppendLine("          .on('mouseenter', (event, lineData) => { highlight(lineData.filePath, true); showTooltip(event, lineData, x); })");
        sb.AppendLine("          .on('mousemove', (event, lineData) => showTooltip(event, lineData, x))");
        sb.AppendLine("          .on('mouseleave', (_event, lineData) => { highlight(lineData.filePath, false); hideTooltip(); })");
        sb.AppendLine("          .append('title')");
        sb.AppendLine("          .text((lineData) => lineData.filePath);");
        sb.AppendLine("        const legend = svg.append('g').attr('transform', `translate(${width - margin.right + 24},${margin.top})`);");
        sb.AppendLine("        const legendItems = legend.selectAll('g')");
        sb.Append("          .data(data.slice(0, ").Append(TopFileLimit.ToString(CultureInfo.InvariantCulture)).AppendLine("))");
        sb.AppendLine("          .join('g')");
        sb.AppendLine("          .attr('class', 'legend-item')");
        sb.AppendLine("          .attr('transform', (_lineData, index) => `translate(0,${index * 16})`)");
        sb.AppendLine("          .on('mouseenter', (event, lineData) => { highlight(lineData.filePath, true); showTooltip(event, lineData, null); })");
        sb.AppendLine("          .on('mousemove', (event, lineData) => showTooltip(event, lineData, null))");
        sb.AppendLine("          .on('mouseleave', (_event, lineData) => { highlight(lineData.filePath, false); hideTooltip(); });");
        sb.AppendLine("        legendItems.append('circle')");
        sb.AppendLine("          .attr('cx', 6)");
        sb.AppendLine("          .attr('cy', 0)");
        sb.AppendLine("          .attr('r', 5)");
        sb.AppendLine("          .attr('fill', (lineData) => color(lineData.filePath));");
        sb.AppendLine("        legendItems.append('text')");
        sb.AppendLine("          .attr('class', 'legend-label')");
        sb.AppendLine("          .attr('x', 18)");
        sb.AppendLine("          .attr('y', 4)");
        sb.AppendLine("          .text((lineData) => lineData.filePath.length > 36 ? `${lineData.filePath.slice(0, 35)}...` : lineData.filePath)");
        sb.AppendLine("          .append('title')");
        sb.AppendLine("          .text((lineData) => lineData.filePath);");
        sb.AppendLine("      };");
        sb.AppendLine("      render();");
        sb.AppendLine("      new ResizeObserver(render).observe(container);");
        sb.AppendLine("    }");
        sb.AppendLine("  </script>");
    }
}

internal sealed class TimeSeriesGraphSeries
{
    public required string FilePath { get; init; }
    public double? AvgDeltaLinesAddedPerBucket { get; init; }
    public double? AvgDeltaLinesRemovedPerBucket { get; init; }
    public required IReadOnlyList<TimeSeriesGraphPoint> Points { get; init; }
}

internal sealed class TimeSeriesGraphPoint
{
    public required string Date { get; init; }
    public double ChurnRiskScore { get; init; }
    public double ChangesPerWeek { get; init; }
    public int LinesAdded { get; init; }
    public int LinesRemoved { get; init; }
    public double? CoveragePercent { get; init; }
    public double? LinesAddedAvgPerCommit { get; init; }
    public double? LinesRemovedAvgPerCommit { get; init; }
}
